### ISSUE TITLE
エラーが発生した時にソースコードの行番号・列番号を表示できるように

### ISSUE THREAD

**Issue by marihachi** [aiscript-dev/aiscript#144]

**Comment by syuilo** [comment]
やりたい

**Comment by marihachi** [comment]
パースエラーについて、正確なエラー位置を表示できるのかは微妙
調べないと

**Comment by marihachi** [comment]
ランタイムエラーは、ASTにソース上の位置が含まれていれば表示できそう

**Comment by marihachi** [comment]
#360 でnode.locを実装した
これを利用してランタイムエラーのエラー位置は出せそう。

パースエラーについても、新パーサーでは処理中の位置を把握しやすくなったため、
実装できそうかも

**Comment by marihachi** [comment]
今度やる
https://github.com/syuilo/aiscript/pull/360#issuecomment-1756740789

**Comment by marihachi** [comment]
構文エラーはエラー位置を表示できた

ランタイムエラーもエラー位置の表示が必要であれば、インタプリタの方でノードや引数から位置情報を渡すように変更する必要がありそう

**Comment by FineArchs** [comment]
>ランタイムエラーもエラー位置の表示が必要であれば、インタプリタの方でノードや引数から位置情報を渡すように変更する必要がありそう

これはこちらでやってみます

**Comment by marihachi** [comment]
ランタイムエラーの場合は表示するかどうかの検討も必要だと思ってるんですがどうでしょう。
インタプリタの場合はいいですが、コンパイラの場合はコードの位置情報は(何か細工をしない限りは)抜け落ちることになるので、処理系としてはインタプリタのみの追加機能になると思います。

**Comment by marihachi** [comment]
コンパイラは関係ない！ということで実装してもいいとは思います。

**Comment by FineArchs** [comment]
AiScriptにコンパイラがあるんですか？
初めて聞きました

**Comment by marihachi** [comment]
WebAssemblyにコンパイルする計画がありましたが実現してませんね... :eyes:
