### ISSUE TITLE
AiScriptのパーサーを再帰下降のLLパーサーとして書き直す？

### ISSUE THREAD

**Issue by marihachi** [aiscript-dev/aiscript#359]
今のPEGパーサーを手書きのパーサーで置き換える。

スペースの扱いとか簡単になって、色々やりやすくなるかも？
Pratt-parserを統合すれば演算子の処理をシンプルにできそう
バックトラックが発生しなくなりパフォーマンスが良くなることを期待できる。

- #360

**Comment by marihachi** [comment]
今までchain系としていた不完全なノードは、パーサーの時点で完全なノードとして処理できるようになりそう(Pratt-parserによって)。

**Comment by marihachi** [comment]
Attrは一旦パーサーの状態として保持して、次に現れたノードに対して付加するようにするか。
状態を保持できる必要があるな

**Comment by marihachi** [comment]
それか、parseAttrで他のパーサー(parseStatement等)をくるんでしまうのもアリ
parseAttrがノードをマージすれば、パーサーに状態を保持する必要はない

**Comment by marihachi** [comment]
CSTが要らなくなるかも

**Comment by marihachi** [comment]
attrは前置演算子として実装すれば良いかも

**Comment by marihachi** [comment]
テンプレートはトークナイズの時点で処理しないとダメそうだなあ

**Comment by marihachi** [comment]
> attrは前置演算子として実装すれば良いかも

これ文に対しての適用だからダメだ

**Comment by marihachi** [comment]
セパレータとしてスペースを使える仕様を忘れてた

**Comment by marihachi** [comment]
#381 の問題があり、一旦実装を中断。

**Comment by marihachi** [comment]
新仕様のmatchを実装

**Comment by marihachi** [comment]
呼び出し構文として処理:
```
[(@() { 1 })(1)]
```

配列として処理
```
[(@() { 1 }) (1)]
```

これを実現するためには、callの前にはスペースを置けないように制限する必要がありそう

**Comment by FineArchs** [comment]
関数と呼び出しの括弧の間にスペースを挟みたい人はいなさそう…多分…と思うので、その位置のスペースの禁止は賛成です。

**Comment by marihachi** [comment]
インデックスアクセスも同じ仕様で良いかも？

**Comment by marihachi** [comment]
#382 で中置演算の途中で改行できるようにしたけど、
実装の都合上やっぱり改行禁止にしたい(元々の動作)。
その方が安全かも。
行末に`\`を付けると改行できる。

**Comment by FineArchs** [comment]
行末の`\`は常に次の改行を打ち消すようになる感じですか？

**Comment by marihachi** [comment]
今までのパーサーの動作から変更はありませんでした
