### ISSUE TITLE
match式の仕様を見直したい

### ISSUE THREAD

**Issue by marihachi** [aiscript-dev/aiscript#381]
Related to #359

主に中置演算子(infix)の構文とぶつかる問題があるため。

以下のようなコードがあるとき
```
match x {
  1 => "a"
  2 => "b"
  * => "c"
}
```
`"b" *`以降の部分が中置演算子として解釈されて、構文エラーになる

これまでは中置演算の途中で改行をはさめないように(エスケープすれば可能)することで、
ぶつかるのをなんとか回避していたが、いっそ仕様を変えてしまいたい。

余談:
新しいパーサーではスペーシングの1つである改行を特別扱いしたくないという気持ちがある
パーサーの複雑化を招く原因になると思う

区切り文字を置けば中置演算子と干渉しなくなる。

コンマ区切り？
```
match x {
  1 => "a",
  2 => "b",
  * => "c",
}
```

セミコロン区切り？
```
match x {
  1 => "a";
  2 => "b";
  * => "c";
}
```

行頭にキーワードを置いても良さそう
この場合は区切り不要にできる
```
match x {
  case 1 => "a"
  case 2 => "b"
  default => "c"
}
```

**Comment by marihachi** [comment]
cc: @syuilo

**Comment by FineArchs** [comment]
キーワードに一票です

>新しいパーサーではスペーシングの1つである改行を特別扱いしたくないという気持ちがある

今まで改行で区切っていた所を全部何らかの区切り文字に置き換えるみたいな感じですか？

**Comment by marihachi** [comment]
> 今まで改行で区切っていた所を全部何らかの区切り文字に置き換えるみたいな感じですか？
少し複雑なんで説明が難しいんですが、
パーサーで文字列中のある部分をどの構文として処理させるかを制御する話です。
match文の各行の構文規則は
```
<式> "=>" <式またはブロック>
```
という形になっています。
`<式またはブロック>`には`1 * 2`のような中置演算も含まれるので、
以下のような入力があった時：
```
match x {
  1 => "a"
  2 => "b"
  * => "c"
}
```
`"b"`, 改行やスペース, `*`と来た段階でその部分は中置演算だろうと誤認識されます。
matchの各行に区切りを導入すればこの誤認識は起こらなくなるだろう、という感じです。

**Comment by FineArchs** [comment]
ありがとうございます。
```
match x {
  1 => "a"
  2 => "b"
  [*] => "c"
}
```
とかもありですかね？

**Comment by marihachi** [comment]
`[]`はインデックスアクセスの意味を持っていますね...
トークナイズの段階で`[*]`の塊で切り出せば問題ないかもです

**Comment by syuilo** [comment]
キーワードかなー

**Comment by marihachi** [comment]
キーワードで区切り不要でいく？
使うキーワードとかどうしようね

**Comment by saki-lere** [comment]
改行で文を区切りを表す以上ある程度特別扱いになるのはしょうがない気もします

**Comment by FineArchs** [comment]
```
match x {
  1 => "a"
  2 => "b"
  else => "c"
}
```
とか…？
個人的には`*`がついていた場所以外は以前同様であって欲しいです（`* =>`を機械的に置き換えるだけで既存スクリプトの修正ができるため）

**Comment by marihachi** [comment]
今のmatch式の仕様が重要であれば、新パーサーでもなんとか処理することも可能かもしれません。
重要ではなければ仕様を変える方が楽です。

**Comment by marihachi** [comment]
構文規則上は式が2つ続くことになるので、今は見つかっていませんが他にも干渉する可能性がありそうです...

**Comment by FineArchs** [comment]
ならやはり
>```
>match x {
>  case 1 => "a"
>  case 2 => "b"
>  default => "c"
>}

が良さそうですかね？（`case`と`else`は見た目が紛らわしいので併用を避けたい）

**Comment by marihachi** [comment]
個人的にはcase defaultが好きです
コンマだと付け忘れが発生するかも？

**Comment by saki-lere** [comment]
`else`は`if-else`と競合して同じ問題が出るので`default`が無難かと
`case`は必要？既存の変数名`default`との区別？

**Comment by marihachi** [comment]
あった方が安全ではあります

**Comment by saki-lere** [comment]
式の連続と考えれば引数リストが空白区切りできるのと同じように無くてもいいはず？
既存コードの変更箇所が増えるので不要なら無くてもいいんじゃないかと思います

**Comment by FineArchs** [comment]
>引数リストが空白区切りできるのと同じように

確かに

**Comment by marihachi** [comment]
主な問題はmatch式の「*」が他の式と誤認識されるという点です。

式の連続は今回の直接の問題ではないですが少し危険な構文規則ということですね。
言われてる通り、他の構文でも使われています。

**Comment by FineArchs** [comment]
将来的にスペース区切りを廃止する可能性があるなら`case`をつけたほうがよさそうですが、
そうでないなら`default`のみの変更がよいように思います。

**Comment by syuilo** [comment]
case / default に一票

**Comment by marihachi** [comment]
> 今のmatch式の仕様が重要であれば、新パーサーでもなんとか処理することも可能かもしれません。
> 重要ではなければ仕様を変える方が楽です。

matchの今の仕様がそこまで重要ではなさそうなので、パースのやりやすさを優先して以下の構文でいきます
```
match x {
  case 1 => "a"
  case 2 => "b"
  default => "c"
}
```

**Comment by syuilo** [comment]
一旦決定したものを蒸し返して申し訳ないけど(リリース前だからまだｷﾞﾘ)、セミコロンの方が良さそうに思えてきた

- 今後言語が発展していった場合、どこかでセミコロン(もしくはその他の文の終わりを示す記号)が必要になるようなケースや構文が出てくる可能性は低くなさそう
  - それなら今の段階からセミコロンに寄せていった方が統一できて良さそう
- default という変数名は割と使われそう
  - これに関しては別のキーワードにする余地もあるけど

**Comment by syuilo** [comment]
意見募集中

**Comment by FineArchs** [comment]
個人的には`;`で区切るか改行で区切るかはどちらかで統一して欲しいですね…
defaultが変数名に使われそうなのはそうかもしれませんが、他のキーワードもだいたいそうなような…？

**Comment by syuilo** [comment]
今改行で区切るとこってあったっけ？

**Comment by syuilo** [comment]
あるとしたら改行で区切るのはいつか限界きそうだからやめたい

**Comment by FineArchs** [comment]
普通の文の区切りが改行だったはずです。
```
<: "Hello World!" //←ここなど
```

**Comment by syuilo** [comment]
あー勘違いしてた

**Comment by FineArchs** [comment]
というか改行区切りに無理があると言うなら、配列や引数の区切りを空白にしていることの方がN万倍は無理があるような…

**Comment by FineArchs** [comment]
実際
```
[1 -2 3 -4 -1 -4 -4 -3]
```
が
```
[-1, -13]
```
と計算されるようなことが起こっていたみたいですし

**Comment by syuilo** [comment]
> 配列や引数の区切りを空白にしていることの方がN万倍は無理があるような…

やめるか

**Comment by saki-lere** [comment]
case-defaultは文の区切りというよりも各ケースの区切りを明示できるので構文解析に有利で良いと思います
文・式の区切りをどうするかはまた別の議題かと思います

**Comment by saki-lere** [comment]
スペース区切りを禁止したら0.12.0レベルで影響が出そう…

**Comment by syuilo** [comment]
> 一旦決定したものを蒸し返して申し訳ないけど(リリース前だからまだｷﾞﾘ)、セミコロンの方が良さそうに思えてきた
> 
> * 今後言語が発展していった場合、どこかでセミコロン(もしくはその他の文の終わりを示す記号)が必要になるようなケースや構文が出てくる可能性は低くなさそう
>   
>   * それなら今の段階からセミコロンに寄せていった方が統一できて良さそう
> * default という変数名は割と使われそう
>   
>   * これに関しては別のキーワードにする余地もあるけど

撤回

**Comment by syuilo** [comment]
(スペース区切りに関してはいつか見直さないといけないときが来そう)

**Comment by marihachi** [comment]
スペース区切り廃止しようぜ

**Comment by FineArchs** [comment]
するなら今のバージョンをリリースした後にしたいです（既に破壊的変更が複数あり、これ以上増えると移行が困難になると思われるため）
自動移行プログラムを提供出来ればまた別ですが…

**Comment by syuilo** [comment]
やるならまとめてやりたい派
AiScriptが一番使われてるのはMisskeyだと思うけど、Misskeyでは現行バージョンのサポートも続ける予定

**Comment by FineArchs** [comment]
そういうことであれば、CHANGELOGに「破壊的変更が多いため過去バージョンとの併用推奨」などと書いておけばとりあえず問題ないですかね

**Comment by marihachi** [comment]
まとめたほうが良いかも
これリバートして次の大型リリースに含める？

**Comment by FineArchs** [comment]
次を大型リリースにするのだと何か問題あります？

**Comment by marihachi** [comment]
いつやるのか不明

**Comment by FineArchs** [comment]
↑ごめんなさい、誤操作です

まあ一度時間を置くのは整理にも繋がっていいのかも…？

**Comment by marihachi** [comment]
Revertしました
issueも開けておきます

**Comment by marihachi** [comment]
#408 としてPR上げ直しました

**Comment by FineArchs** [comment]
↑ごめんなさい、また誤操作です…

**Comment by marihachi** [comment]
新パーサーからの実装でいきます
