### ISSUE TITLE
スペースや改行による区切りをやめる？

### ISSUE THREAD

**Issue by marihachi** [aiscript-dev/aiscript#402]

**Comment by FineArchs** [comment]
空白区切りはいいとして、改行区切りは代わりに何を使うのかという問題がありますね。
セミコロンが一番わかりやすいとは思いますが、既存の引数や配列の要素を区切る用法ではコロンとセミコロンを同一視しているため、「こっちでは両方使えるのにあっちでは片方しか使えない」という状況になってやや反直観的に思います。

**Comment by saki-lere** [comment]
改行区切りは空白区切りと比べて曖昧さが小さいので無くす必要は無いと思います

**Comment by FineArchs** [comment]
そういえばmatch文をセミコロン区切りに変える話は撤回されたんでしたね…
では改行区切りはそのままでよさそうですね

**Comment by marihachi** [comment]
改行区切りというのはどこでやってますかね
リストアップしましょうか

**Comment by FineArchs** [comment]
- 文と文の区切り
- match文
- //のコメント

くらいですかね？

**Comment by saki-lere** [comment]
改行でしか区切れないのは文同士だけだと思います
空白とともに改行も使えるのは
- 仮引数(識別子-識別子)
- 配列、オブジェクト、実引数 (式-式)
- if、for 、each (式-文)

かと
matchは空白でもよかったはず

**Comment by FineArchs** [comment]
> matchも空白でよかったはず

そうでした

**Comment by marihachi** [comment]
文と文の間は改行以外でも区切れるべきかもと思いました
ワンライナーとかの場合、一行でかけたほうが嬉しいかも？

**Comment by marihachi** [comment]
行の区切り以外でセミコロンを使えないように変更すれば、
統一性は改善できそうです

**Comment by FineArchs** [comment]
shell scriptみたいな使用感になりそうですね
いいと思います

**Comment by marihachi** [comment]
@syuilo どうじゃろ

**Comment by syuilo** [comment]
JSみたいにセミコロンあってもなくてもよい(ただ稀に無いと正しく解釈されないケースが存在する)という感じ？

**Comment by saki-lere** [comment]
原則改行は常に文終端、`;`で同じ行に書ける
が良いかと思います

**Comment by marihachi** [comment]
ブロックやトップレベルの中で、文が2つ以上あればそれらを改行またはセミコロンで区切るって感じ

**Comment by marihachi** [comment]
そういえば宣言文の途中で改行できる仕様あったような...

**Comment by syuilo** [comment]
YOSASOU

**Comment by marihachi** [comment]
配列、オブジェクト、引数の区切りは
`,`か改行で区切るように統一で良いですか？

**Comment by FineArchs** [comment]
いいと思います
