### ISSUE TITLE
今後キーワードとして使う可能性のある識別子は予約語として登録する

### ISSUE THREAD

**Issue by marihachi** [aiscript-dev/aiscript#407]
重要かも

### 追加で良さそう
`as`
`async`
`await`
`case`
`catch`
`component`
`constructor`
`default`
`dictionary`
`do`
`enum`
`finally`
`hash`
`in`
`interface`
`out`
`private`
`public`
`ref`
`table`
`this`
`throw`
`trait`
`try`
`undefined`
`use`
`using`
`when`
`yield`
`is`
`new`

### 却下
`map`
`any` (型名限定)
`error` (型名限定)
`unknown` (型名限定)
`value` (型名限定)
`void` (型名限定)
`get` (文脈キーワード)
`set` (文脈キーワード)

## 型名限定について
型名限定であれば、専用のトークンにするのではなく組み込み型名として登録すれば良いかも？
型システムが進んできたときで良さそう

## 文脈キーワードについて
通常の識別子だが特定の構文ではキーワードとして機能する

**Comment by FineArchs** [comment]
https://github.com/syuilo/aiscript/blob/5b33c6f96114c99e170950177ecf0fa0e7991f61/src/parser/plugins/validate-keyword.ts#L24-L42

このあたりは既に登録されていますね
caseとdefaultは #360 でトークン化するとして、
あとはisとかasとか？

**Comment by marihachi** [comment]
isいりますね

**Comment by marihachi** [comment]
using

**Comment by FineArchs** [comment]
`do`
`any` `value` `undefined` `unknown`

**Comment by marihachi** [comment]
valueは影響範囲すごそう...

**Comment by marihachi** [comment]
一覧に加えました

**Comment by marihachi** [comment]
OOP関連
`new` `constructor` `this` `interface` `trait` `component`

**Comment by marihachi** [comment]
連想配列
`map` `hash` dictionary`

**Comment by marihachi** [comment]
影響が大きそうな語は追加をよく検討するとして、AiScript Nextのリリースのタイミングで予約後の追加も行いますかね？

**Comment by FineArchs** [comment]
`value`も型名として使う（any - error　または　anyを集合論から外れる型とした場合、全集合型)ことを考えているので、型名限定でいいと思います

**Comment by saki-lere** [comment]
`is` 単体使用は少なそう
`map` 高階関数と被る
`new` 必要？
`value` 参照↔値を連想して分かりにくい
型を識別子として記述する場所は少ないので予約語にする必要性は薄いと思います。
文脈キーワードにするという方法もあるかと

**Comment by saki-lere** [comment]
議題とは関係ないですが型を集合扱いするのはあまりよくない気がします
詳しいわけじゃないので何とも言えませんが

**Comment by FineArchs** [comment]
`is` `value is Type`構文で使いたい
`map` 連想配列を表現する他の言葉が思い浮かばない（既存のobjを連想配列として拡張する手もある？）
`new` OOPをするなら`new ClassName()`で使いたい
`value` ドキュメント等では既に使われている、参照型に対する値型として使うにしてもいずれにせよ予約語化したい

型名も紛らわしいので全体で予約語化したい気持ちもありますが、現状の型名の使用箇所の少なさを鑑みてひとまずは型名限定の文脈キーワードにしてもいいと思います。

> 議題とは関係ないですが型を集合扱いするのはあまりよくない気がします

型は集合扱いしたほうが計算しやすそうなので出来るだけ集合として扱いたいです（型同士が包含関係、型に対する値がis_a関係）

**Comment by saki-lere** [comment]
連想配列: associative array, table, dictionary
単に`ClassName()`でコンストラクタ呼び出しにすることもできるはずです
(型理論的に集合と言い切ってしまうのは少しもやもやするなというだけです)

**Comment by saki-lere** [comment]
予約語を増やしすぎるのは良くない&要不要を考え出すときりがない のでとりあえず衝突しにくそうなものだけ予約語にするのがいいと思います

**Comment by marihachi** [comment]
> 単にClassName()でコンストラクタ呼び出しにすることもできるはずです

これは可能ですがAiScriptでもそうなるとは限りません

**Comment by marihachi** [comment]
型名限定のものは予約語にしなくても良いんじゃないかと思います。
型名を宣言する機能が今はないので、どちらでもいいですが...

unknownやvoidも型名でいいですよね？

**Comment by marihachi** [comment]
mapの追加はやめときますかね

**Comment by FineArchs** [comment]
> 型名を宣言する機能が今はないので

一応宣言だけならできませんでしたっけ？（機能していませんが）

**Comment by marihachi** [comment]
ユーザー定義型ですね

**Comment by FineArchs** [comment]
>ユーザー定義型ですね

そういえばこれがないので型名限定の予約語を作る意味が無いんでした…

**Comment by marihachi** [comment]
型名限定については外しましょうか

**Comment by FineArchs** [comment]
`finnaly`は`finally`でいいですか？

**Comment by marihachi** [comment]
直しました

**Comment by FineArchs** [comment]
`get` `is` `set`
欲しい＋そんなに使ってる人いる…？という感じなので追加したい

`new`
使う可能性があるが回避もできる＋`old`と一緒に使っている人が多そうなので除外で良いかも

**Comment by marihachi** [comment]
文脈キーワードって話が出たのは、パーサーでの扱いとしては識別子トークンとして持っておいて、特定の構文でだけそれをキーワードとして扱うという認識ですかね？

**Comment by marihachi** [comment]
技術的に可能そうな気はします

**Comment by FineArchs** [comment]
>文脈キーワードって話が出たのは、パーサーでの扱いとしては識別子トークンとして持っておいて、特定の構文でだけそれをキーワードとして扱うという認識ですかね？

私もその認識です

**Comment by marihachi** [comment]
`new`は何かを生成する関数名として使われてそうだなというイメージで要検討にしました

**Comment by marihachi** [comment]
`new` `is` `get` `set`は文脈キーワードとしますかね

**Comment by marihachi** [comment]
いやでも`is`は単体使用無いかも

**Comment by saki-lere** [comment]
`new` `is`は式内で使うものだから構文上区別できても視覚的には分かりにくそう

**Comment by marihachi** [comment]
つまり、`new` `is`は変数名などに使えないようにした方が良さそうということですかね？

**Comment by FineArchs** [comment]
>`new` `is`は式内で使うものだから構文上区別できても視覚的には分かりにくそう

となると両方キーワードに追加したほうがいい…？

**Comment by marihachi** [comment]
ですねキーワードにしますか

**Comment by FineArchs** [comment]
`get` `set`は文脈キーワードにすべき文脈（クラスや"ゲッター・セッターを持つようなオブジェクト相当の概念"のプロパティ）がまだ存在していないので取り敢えずは放置で良さそうですかね？
（AiScriptのオブジェクトは実質文字列専用の連想配列のようなもののため）

**Comment by marihachi** [comment]
却下に入れておきました
だいたい検討は良さそうですかね

**Comment by saki-lere** [comment]
`dictionary` `table` `hash`は型名扱い？

**Comment by marihachi** [comment]
今は`&{  }`みたいな構文で進んでいますが、ここが`table {  }`みたいに変わるかもと思って追加してます

**Comment by FineArchs** [comment]
>`dictionary` `table` `hash`

宣言で使う可能性があると思います

**Comment by MineCake147E** [comment]
`switch` `goto` `default`
以下のような`switch`文を導入する際に使う可能性があると思います
```
switch (p)
{
    case 1:
        y += 1
        return y
    case 2:
        y += 2
        goto case 1
    default:
        return x
}
```

**Comment by saki-lere** [comment]
match式が既にあるので不要かと思います
misskeyの`Ui:C:switch`ともぶつかります
