### ISSUE TITLE
Playgroundをデプロイ出来ていない

### ISSUE THREAD

**Issue by FineArchs** [aiscript-dev/aiscript#431]
[Github PagesのActionが落ちてるっぽいです。](https://github.com/aiscript-dev/aiscript/actions/runs/6582496581)

[私のリポジトリでは問題なく動いている](https://github.com/FineArchs/aiscript)のでリポジトリの設定が原因？

memberではいじれないっぽいので @syuilo さんよろしくお願いします。

**Comment by FineArchs** [comment]
@syuilo 多分Settings → Actions → general → Workflow permissionsをRead and write permissionsにする？

**Comment by syuilo** [comment]
![IMG_4802](https://github.com/aiscript-dev/aiscript/assets/4439005/f46fac0f-0abb-4bdf-ae7e-76adf3a6c92c)
選択できなかった

**Comment by marihachi** [comment]
それなんかあった気がする

**Comment by marihachi** [comment]
org側の設定が効いてて設定が無効になるみたいな感じだった気がする

**Comment by FineArchs** [comment]
@syuilo organizationのページにも同じような設定画面があるようなので、そちらで先程の設定をすればよさそうです

**Comment by syuilo** [comment]
done
