### ISSUE TITLE
同一スコープ内での変数の再宣言が認められないことをドキュメントに明記する

### ISSUE THREAD

**Issue by sorairolake** [aiscript-dev/aiscript#451]
```
let bar = "Hello"
let bar = bar.len // Runtime: Variable 'bar' is alerady exists in scope '<root>'
```

や

```
var foo = 42
var foo = foo.to_str() // Runtime: Variable 'foo' is alerady exists in scope '<root>'
```

のように、同一スコープ内で宣言済みの変数と同じ名前の変数を再宣言しようとすると、`AiScriptRuntimeError`が発生します。同一スコープ内で変数の再宣言ができるプログラミング言語 (JavaScriptの`var`や関数型プログラミング言語のシャドーイングなど) もあるので、これが認められないのがAiScriptの仕様である場合は、構文についてのドキュメントにこのことを記載しておくと分かりやすいと思います。

**Comment by FineArchs** [comment]
https://github.com/aiscript-dev/aiscript/commit/983fa50225f8dba2562c268d3038f8f5a89e15e7
取り急ぎ記載しました。
