### ISSUE TITLE
文字列とUnicodeに関する関数の拡充 Additional functions to manipulate string with Unicode code points

### ISSUE THREAD

**Issue by MineCake147E** [aiscript-dev/aiscript#483]
## 概要

https://github.com/aiscript-dev/aiscript/pull/313 で`str.codepoint_at`が追加されましたが、何故か[charCodeAt()](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/String/charCodeAt)を呼び出しており、UTF-16の上位サロゲートをそのまま返してしまいます。
https://github.com/aiscript-dev/aiscript/blob/537fa96b3990fe55a7bebd1864f12ac87144b876/src/interpreter/primitive-props.ts#L77-L82
![image](https://github.com/aiscript-dev/aiscript/assets/31585494/23801a2c-6842-40c1-8f9c-7ad67b7ed959)
他、Unicodeコードポイントによる文字位置指定が現状できないことから、
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/@@iterator
と同じことがAiScriptでも出来るようになったらいいなと思いました。
また、他にもいくつかの関数を提案します。

### `str.unicode_codepoint_at(index)`
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/String/codePointAt
`str.codepoint_at`とは違い、`index`の位置の要素が UTF-16の上位サロゲートであった場合、そのサロゲート**ペア**のコードポイントを返す。
```is
"𩸽".unicode_codepoint_at(0) // 171581
```
戻り値は`num`。

### `str.to_arr()`
**AiScriptの**`str.split()`と同じ挙動をする。
書記素クラスタは保持される。
```is
"𩸽👉🏿👨‍👦".to_arr() // ["𩸽", "👉🏿", "👨‍👦"]
```
戻り値は`str`の配列。

### `str.to_unicode_arr()`
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/@@iterator と同じ挙動をする。
書記素クラスタは分割されるが、サロゲートペアは保持される。
```is
"👉🏿".to_arr() // ['👉', '🏿']
```
戻り値は`str`の配列。

### `str.to_unicode_codepoint_arr()`
```is
str.to_arr().map(@(a) {a.unicode_codepoint_at(0)})
```
```is
'𩸽👉🏿👨‍👦'.to_unicode_codepoint_arr() // [171581, 128073, 127999, 128104, 8205, 128102]
```
戻り値は`num`の配列。

### `str.to_char_arr()`
**JavaScriptの**[`string.split("")`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split)と同じ挙動をする。
サロゲートペアは分割される。
※AiScriptの`str.split("")`でもサロゲートペアは分割される
```is
"😄".to_char_arr() // [55357, 56836].map(@(a) {Str:from_codepoint(a)})
```

### `str.to_charcode_arr()`
`str.codepoint_at`をすべての文字に対して実行し、数値の配列を返す。
サロゲートペアは分割される。
```is
"😄".to_charcode_arr() // [55357, 56836]
```

### `str.to_utf8_byte_arr()`
文字列をUTF-8のバイト毎に分割し、数値の配列を返す。
```is
"𩸽".to_utf8_byte_arr() // [240, 169, 184, 189]
```

### `Str:from_unicode_codepoints(array)`
```is
arr.map(@(a) {Str:from_codepoint(a)}).join()
```
```is
Str:from_unicode_codepoints([171581, 128073, 127999, 128104, 8205, 128102]) // "𩸽👉🏿👨‍👦"
```

### `Str:from_utf8_bytes(array)`
`num`の`arr`を受け取り、UTF-8をデコードして文字列を作成する。
```is
Str:from_utf8_bytes([240, 169, 184, 189]) // "𩸽"
```

**Comment by marihachi** [comment]
現行の関数の動作は修正したほうが良いかもです

**Comment by marihachi** [comment]
ユニコード非対応の関数を提供する必要があるのかというところですね

**Comment by marihachi** [comment]
あとは糖衣構文的な便利な組み込み関数を組み込み機能として入れるのかという部分も検討されるべきです

**Comment by FineArchs** [comment]
Unicodeについてあまりよく分かっていないのですが、例えば"👉🏿"はUnicodeのコードポイントでは一つの数字で表せるのですか？

**Comment by ikasoba** [comment]
`str.codepoint_at`は僕のミスですね
`str.unicode_codepoint_at`を`str.codepoint_at`に改名したほうが良さそう？

**Comment by ikasoba** [comment]
もし改名するなら、`str.charcode_at`も追加したほうが良さそう

**Comment by MineCake147E** [comment]
> 例えば"👉🏿"はUnicodeのコードポイントでは一つの数字で表せるのですか？

"👉🏿"は内部的には2文字です。”U+1F449 WHITE RIGHT POINTING BACKHAND INDEX”の後ろに`U+1F3FF EMOJI MODIFIER FITZPATRICK TYPE-6`が続いており、これらが一文字であるように表示されています。
このように、複数文字のシーケンスを一文字として表示する「書記素クラスタ」という概念がUnicodeには存在します。

**Comment by MineCake147E** [comment]
> 現行の関数の動作は修正したほうが良いかもです

現行ドキュメントとの矛盾を解決することを優先するならそれが良いと思います。

> あとは糖衣構文的な便利な組み込み関数を組み込み機能として入れるのかという部分も検討されるべきです

恐らく`str.to_unicode_codepoint_arr()`等についてのご意見だと思われますが、個人的にはMisskey Playのように実行速度制限がかかる状況においてAiScriptでやることは可能な限り減らしたいです。
`Math`内の関数の殆どがネイティブ実装されているのも同様の利点があると思います。

**Comment by FineArchs** [comment]
> 現行の関数の動作は修正したほうが良いかもです
> str.unicode_codepoint_atをstr.codepoint_atに改名したほうが良さそう？

賛成です。

**Comment by FineArchs** [comment]
to_arrは書記素クラスタ単位での分割を行う関数にしてほしいです。よりシンプルな名前の機能はより直観的であるべきです。
stringzに同名の関数があるので、それを利用するようにお願いします。

**Comment by MineCake147E** [comment]
> to_arrは書記素クラスタ単位での分割を行う関数にしてほしいです。よりシンプルな名前の機能はより直観的であるべきです。

同様の機能は`split("")`で既に存在しますが、確かに`split("")`では分かりづらいかもしれませんね。

**Comment by FineArchs** [comment]
https://github.com/MineCake147E/aiscript/pull/1

@marihachi @saki-lere @syuilo 
異論ある方はいますか？

**Comment by FineArchs** [comment]
@syuilo @saki-lere 
認識合わせのため https://github.com/MineCake147E/aiscript/pull/1 について説明を加えておくと、

用語
- コードポイント：Unicodeにおける各文字の番号。`U+XXXX`の形式で表される
- サロゲートペア：'👉'などのUnicodeのコードポイントがある値より大きい文字は、UTF-16では二文字分の領域を使って表される。その時の上位16bitを上位サロゲート、下位16bitを下位サロゲート、合わせてサロゲートペアと呼ぶ。
- 書記素クラスタ：例えば'👉🏿'という文字は、'👉'に'🏿'(U+1F3FF)という文字を組み合わせて成り立っている。このようなコードポイント自体が２つある文字を書記素クラスタと呼ぶ。

現状
- AiScriptにおける多くの文字列操作は、stringzというライブラリにより書記素クラスタ単位での操作を実現している。
- だが、`str.codepoint_at`はサロゲートペアを分割してカウントするため、'👉'などの文字が崩れてしまう。
- `str.codepoint_at`は書記素クラスタも分割するが、これに関しては「コードポイントに変換する」という機能上どうしようもない

https://github.com/aiscript-dev/aiscript/pull/486
- `str.codepoint_at`は現状のまま保存。
- サロゲートペアを分割しない関数`str.unicode_codepoint_at`を追加。

https://github.com/MineCake147E/aiscript/pull/1 ( #486 へのPR )
- `str.codepoint_at`の現状の挙動をバグとみなし、サロゲートペアを分割しないように修正。
- 今までの`str.codepoint_at`と同様の挙動をする`str.charcode_at`を追加。

とりあえずこの２つのどちらを選ぶか決めたい感じです。
