### ISSUE TITLE
apologies: NPM_SECRETを消してしまったので再発行をお願いします

### ISSUE THREAD

**Issue by FineArchs** [aiscript-dev/aiscript#495]
自分のフォークに設定していたテスト用のシークレットを消そうとして、誤ってこのリポジトリのシークレットを消してしまいました。
再発行と再設定をお願いします。（ごめんなさい）

> githubでのトークン名： `NPM_SECRET`

> npmでのトークンの設定：
> - 種類 Granular Access Token
> - 有効期間 2028/12/31 (頻繁に更新しなくて良いように5年とか？)
> - スコープ @syuilo/aiscriptパッケージのみread/write

**Comment by syuilo** [comment]
少々お待ちを

**Comment by syuilo** [comment]
done

**Comment by FineArchs** [comment]
🙏

**Comment by FineArchs** [comment]
> https://github.com/aiscript-dev/aiscript/actions/runs/7078740469
> 
> npm publishが失敗しているようです。 状況的にトークンの問題である可能性が高い（権限のスコープが間違っている？）ので、再発行お願いします。

@syuilo よろしくお願いします。

**Comment by FineArchs** [comment]
うーん、とするとgithubのシークレットとして登録する際に何かしらのアクシデントが起こった？

**Comment by syuilo** [comment]
再設定してみた

**Comment by FineArchs** [comment]
改善しないですね…

**Comment by FineArchs** [comment]
さっきのスクショを見る限り、Last usedには反映されているんですよね

**Comment by syuilo** [comment]
謎

**Comment by syuilo** [comment]
どっかでなんらかのキャッシュが残ってるとかかしら
エラーログとかないかしら

**Comment by syuilo** [comment]
あー

**Comment by syuilo** [comment]
これで直ったはず

**Comment by FineArchs** [comment]
無事発行できました！！
