### ISSUE TITLE
そろそろ0.17.0をリリースしたい

### ISSUE THREAD

**Issue by FineArchs** [aiscript-dev/aiscript#517]
結構変更が溜まってきたので、そろそろ0.17.0をリリースしたいです。
> # 0.17.0
> - `package.json`を修正
> - `Error:create`関数でエラー型の値を生成できるように
> - `Obj:merge`で２つのオブジェクトの併合を得られるように
> - Fix: チェイン系（インデックスアクセス`[]`、プロパティアクセス`.`、関数呼び出し`()`）と括弧を組み合わせた時に不正な挙動をするバグを修正
> - 関数`Str#charcode_at` `Str#to_arr` `Str#to_char_arr` `Str#to_charcode_arr` `Str#to_utf8_byte_arr` `Str#to_unicode_codepoint_arr` `Str:from_unicode_codepoints` `Str:from_utf8_bytes`を追加
> - Fix: `Str#codepoint_at`がサロゲートペアに対応していないのを修正
> - 配列の範囲外および非整数のインデックスへの代入でエラーを出すように

**Comment by marihachi** [comment]
機能追加とかはNextに含めたほうが良いような気がします
どう思いますか？

**Comment by FineArchs** [comment]
個人的には先延ばしにする理由が思い浮かばないので通常リリースに含めて問題ないと思っています。
本家ドキュメントに記述があるのに使えない機能があることで混乱が起こっているのをたまに見かけますし…

**Comment by FineArchs** [comment]
@marihachi 
> 機能追加とかはNextに含めたほうが良いような気がします
理由があれば聞いていいですか？

**Comment by saki-lere** [comment]
破壊的だからNextを用意したという流れだったはずなので普通の機能追加はここで反映してもいいかと思います

**Comment by marihachi** [comment]
nextには現行の実装の再実装も含まれるので、機能を追加するとそちらにも実装が必要になることがあるのでちょっと無駄な気もします

**Comment by FineArchs** [comment]
それはそうですね…

**Comment by marihachi** [comment]
パーサーに変更を加えるような機能はnextからの導入が良いかと...
それ以外は現行に取り込んでも問題はないと思います

**Comment by FineArchs** [comment]
パーサーに変更を加える場合はNext優先、やる気があれば現行版を用意してもよい、ただし現行パーサーのバグ修正はこれに限らずという感じでよさそうですかね

**Comment by marihachi** [comment]
そうですね
あとは、現行版でパーサー変更ありの機能追加をした場合はnext側の変更もお願いしたいです。いずれは必要になります。

**Comment by FineArchs** [comment]
>現行版でパーサー変更ありの機能追加をした場合はnext側の変更もお願いしたいです。いずれは必要になります。

今あるやつだと何かありましたっけ

**Comment by FineArchs** [comment]
@syuilo そろそろリリースどうでしょう？

**Comment by syuilo** [comment]
するか

**Comment by FineArchs** [comment]
@syuilo #482 でpackage.jsonのversionは先行して書き換えてあるので、
[std.ts](https://github.com/aiscript-dev/aiscript/blob/master/src/interpreter/lib/std.ts)の`Core:v`だけ書き換えてからpublishしてください（playgroundのバージョン表示は`Core:v`を参照しているので問題ありません）

**Comment by FineArchs** [comment]
もしくは #493 をマージすれば`npm build`の時に`Core:v`をpackage.jsonと同期するようになります

**Comment by syuilo** [comment]
リリースしました

**Comment by marihachi** [comment]
> > 現行版でパーサー変更ありの機能追加をした場合はnext側の変更もお願いしたいです。いずれは必要になります。
> 
> 今あるやつだと何かありましたっけ

把握してません...

**Comment by FineArchs** [comment]
> > > 現行版でパーサー変更ありの機能追加をした場合はnext側の変更もお願いしたいです。いずれは必要になります。
> > 
> > 
> > 今あるやつだと何かありましたっけ
> 
> 把握してません...

私の把握している範囲だとmaster向けのコミット・PRでnext側の対応が必要なものは特にないはず…

**Comment by marihachi** [comment]
> > > > 現行版でパーサー変更ありの機能追加をした場合はnext側の変更もお願いしたいです。いずれは必要になります。
> > > 
> > > 
> > > 今あるやつだと何かありましたっけ
> > 
> > 
> > 把握してません...
> 
> 私の把握している範囲だとmaster向けのコミット・PRでnext側の対応が必要なものは今の所特にないはず…

確認したところ大丈夫そうでした
