### ISSUE TITLE
テンプレート初行・末尾の改行を許容したい

### ISSUE THREAD

**Issue by FineArchs** [aiscript-dev/aiscript#523]
現行の実装では
```
`{ // <- Syntax Error
  'hoge' // <- Syntax Error
}`
```
のようなテンプレートはunexpected tokenのエラーになりますが、複数行にわたる式を埋め込む場合など、式前後を改行できたほうが見やすい場合は少なくないと思うので、改行可にしたいです。

**Comment by marihachi** [comment]
これバグっぽい
