### ISSUE TITLE
feat: 関数同士の比較を行えるようにしたい

### ISSUE THREAD

**Issue by ikasoba** [aiscript-dev/aiscript#527]
現在の実装だと関数同士の比較は常にfalseを返すのでなんとかしたい
https://github.com/aiscript-dev/aiscript/blob/aiscript-next/src/interpreter/util.ts#L89

一応リリースされているもの仕様を変えることになるので破壊的変更としてnextの方へPRを出したほうが妥当かもしれない？
<sub>もっと早くに気づければよかった・・・てへぺろ</sub>

**Comment by ikasoba** [comment]
とりあえずnextへのPRとして実装します

**Comment by FineArchs** [comment]
`==`ならJavaScriptの等号で判定、`===`ならdeep-equalのように分ける手もある

**Comment by ikasoba** [comment]
deep-equalの場合は処理内容が一致する必要があるって感じでしょうか

**Comment by ikasoba** [comment]
そっちだと`==`のニュアンスが近いか

**Comment by ikasoba** [comment]
javascriptだと`===`は厳格な評価を意味するので処理内容さえ合えばいいという曖昧な評価方法は`==`のが自然かもしれないと思った

**Comment by ikasoba** [comment]
なるほどです

**Comment by ikasoba** [comment]
あれ、aiscriptには`===`演算子の実装はなさそうです。

**Comment by FineArchs** [comment]
> あれ、aiscriptには===演算子の実装はなさそうです。

なので生やしちゃおうかなって…

**Comment by ikasoba** [comment]
===演算子はまた別の機会にしたいかもしれない

**Comment by FineArchs** [comment]
じゃあ`A deepeq B`とか？

**Comment by FineArchs** [comment]
#460 を改変すれば技術的には可能なはず

**Comment by ikasoba** [comment]
僕としてはdeep-equal用の演算子を追加するのは便利で良いものだと思うけど、関数同士の比較と一緒にやるのはヘンかと思ったんですよね

**Comment by ikasoba** [comment]
なので===演算子の件は別のissueとして議論したい

**Comment by ikasoba** [comment]
それじゃあissue切っておきますね

**Comment by ikasoba** [comment]
#528 立てました

**Comment by FineArchs** [comment]
関数の`==`は配列・オブジェクト同様、JavaScriptの等号による比較でよさそうですかね

**Comment by ikasoba** [comment]
`Core:eq`で行う評価基準の話であれば、僕としては参照比較で良いかと思いますね

**Comment by ikasoba** [comment]
明後日までになにか問題がなければ実装に取り掛かりますね
