### ISSUE TITLE
notice: nextで演算子の優先順位が変わっている

### ISSUE THREAD

**Issue by FineArchs** [aiscript-dev/aiscript#532]
今見つかっているものでは
```
!false && !true // 現行はtrue, nextはfalse
```
現行は`!(false && !true)`だったのが`(!false) && (!true)`になったということだと思われるのでその旨をそのうちドキュメントに追記しておきたい

**Comment by marihachi** [comment]
優先順位表を作ると良さそう

**Comment by FineArchs** [comment]
[syntax.md](https://github.com/aiscript-dev/aiscript/blob/master/docs/syntax.md)に演算子の項目を追加するのが妥当？
[get-started](https://github.com/aiscript-dev/aiscript/blob/master/docs/get-started.md#%E6%BC%94%E7%AE%97)の演算子リストに追記してもいいかもだけどgetting startedというにはカロリー高めな気がするし

**Comment by marihachi** [comment]
syntax.mdに演算子の項目を増やして、そこに追加するのが良いかも
