### ISSUE TITLE
マージしていい条件を緩和

### ISSUE THREAD

**Issue by FineArchs** [aiscript-dev/aiscript#554]
#499 
> ソースコード及びテストの変更は、
非破壊的変更であればmember2人以上の同意＆1日の経過を待ち、非memberを含む反対者が同意者の半数以下ならマージしてよい
破壊的変更であればmember3人以上の同意＆1日の経過を待ち、非memberを含む反対者が同意者の4分の1以下ならマージしてよい

この部分について、
- 現状を鑑みると条件が厳しすぎる
- 破壊的変更はnextに入れる以上、非破壊的変更より厳しくする必要性が薄い
- 「同意」=approveと明確化したい

よって以下のように緩和したいです。

> ソースコード及びテストの変更は、
破壊的・非破壊的問わずmember（PR作成者本人除く）1人以上のapprove＆1日の経過を待ち、非memberを含む反対者が同意者の半数以下ならマージしてよい

**Comment by marihachi** [comment]
破壊的変更は少し慎重になるべきなので、2人以上のapproveとした方がよさそうです

> ソースコード及びテストの変更は、
非破壊的変更であればmember（PR作成者本人除く）1人以上のapprove＆1日の経過を待ち、非memberを含む反対者が同意者の半数以下ならマージしてよい
破壊的変更であればmember（PR作成者本人除く）2人以上のapprove＆1日の経過を待ち、非memberを含む反対者が同意者の半数以下ならマージしてよい

**Comment by marihachi** [comment]
反対/賛成ってGitHubコメント上の意見やリアクションのことを指してますか？
approveはコードに問題がないかをチェックする工程だと思うので、賛成反対を直接指しているわけではない気がします。
(たとえば、レビューをしてapproveはしないが賛成する場合もある)

**Comment by FineArchs** [comment]
> 緩和には賛成ですが、2人以上のapproveとした方がよさそうです。

OKです。
> 反対/賛成ってGitHubコメント上の意見やリアクションのことを指してますか？

先程は『「同意」=approveと明確化したい』と言いましたが、『非memberを含む…』の下りも巻き込まれることを失念していました。
お察しの通り、前半部の「同意」はapprove、後半部の「反対/同意（賛成）」はコメント・リアクションによる意見表明を意図していました。
つまり、最終的にmarihachiさんの修正案の通りになります。

**Comment by saki-lere** [comment]
「マージ条件の変更」も同じルールでやりますか？
少し厳しめに設定した方が安全かと思います

**Comment by FineArchs** [comment]
確かにルール自体を容易に変更できるとルールの意味がないですね、そうしましょうか

**Comment by FineArchs** [comment]
>「マージ条件の変更」も同じルールでやりますか？
>少し厳しめに設定した方が安全かと思います

以前の条件だとソースコードより条件が緩かったのでソースコードと同格に格上げしようという意味と解釈して上の回答をしましたが、もしかしてソースコードよりさらに厳しくしたほうがいいという意味でしたか？

**Comment by saki-lere** [comment]
一番厳しくあるべきなので「3人以上」などでもいいと思います

**Comment by FineArchs** [comment]
うーん、今の状態で３人集めるのってかなり難しそうな気がするんですよね
このルール自体があまり試運転されていないものなので、最初からガチガチにしすぎると後で修正が効かなくて困りそうな気がします
１年程度年季を積んだら３人にしてもいいと思いますが今は２人にしておきたいです
一応「一番厳しい条件」ではありますし

**Comment by salano-ym** [comment]
ソースの変更を伴うバグ修正は2人以上のapproveが必要という解釈でいいでしょうか？
> - バグ修正、ドキュメントの編集、バージョン更新、dependabotのPRはmember1人の判断でマージしてよい
> - ソースコード、テスト、本規則自体の変更は、member 2人以上のapproveを受けてから1日の経過を待ち、非memberを含む反対者が賛成者の半数以下ならマージしてよい
> - 上記以外の変更はmember 1人以上のapproveを受けてから1日の経過を待ち、非memberを含む反対者が賛成者の半数以下ならマージしてよい

**Comment by FineArchs** [comment]
> ソースの変更を伴うバグ修正は2人以上のapproveが必要という解釈でいいでしょうか？

いえ、明確なバグの修正だけであれば独断でもよいという意図でした。（bugfixはしばしば急を要するため）
