### ISSUE TITLE
Date系関数で返される値が壊れる可能性がある

### ISSUE THREAD

**Issue by marihachi** [aiscript-dev/aiscript#555]
Date系関数は、関数が呼び出された時点の時刻において指定されたパート(分や秒など)の値を取得します。
つまり、各関数はそれぞれ別の時刻データに対して値を算出しているので、
関数を順番に呼び出している間に時刻の桁が繰り上がるとデタラメな時刻が返される可能性があります。

```
// time: 10:59:59
let h = Date:hour()
// time: 11:00:00
let m = Date:minute()
let s = Date:second()

<: `{h}, {m}, {s}` // => 10, 0, 0
```

どうせならAPIを見直した方が良いかもしれません

**Comment by FineArchs** [comment]
> ## @Date:second(date?: num): num
> 現在時刻の秒を取得します。
date を渡した場合、_date_に対応する秒、
渡していない場合は現在時刻の秒が返されます。

つまり、現行のAPIでも
```
// 現在時刻を数値として取得
let time = Date:now()
// 取得した時刻から時・分・秒を取得
let h = Date:hour(time)
let m = Date:minute(time)
let s = Date:second(time)
```
のようにすることでこの問題に対処可能になっています。

**Comment by marihachi** [comment]
え、そんなAPIあったんですね
なら問題なさそうです
