### ISSUE TITLE
文字列系・ユニコード系APIの変更の提案

### ISSUE THREAD

**Issue by marihachi** [aiscript-dev/aiscript#566]
APIの名前を変更します。

## 方針
- よく使うであろうコードポイント単位の操作は短く命名を変更します。
- 文字列を扱う時、通常はコードポイント単位(または書記素クラスタ単位)で扱ってほしいことがほとんどだと思うので、
UTF-16系のAPIの命名を長めに変更します。
- 文字列を分割して返すAPIには`split`という名前を割り当てます。
- charcode、codepointという命名の分け方をやめ、charcodeで統一します。
  - UTF-16はutf16_charcodeのように前置します。

### Unicodeのコードポイントから文字
現 `@Str:from_codepoint(codepoint: num): str`
新 `@Str:from_charcode(codepoint: num): str`

### Unicodeのコードポイント列から文字列
現 `@Str:from_unicode_codepoints(codePoints: arr<num>): str`
新 `@Str:from_charcode_arr(codePoints: arr<num>): str`

### 書記素クラスタ毎に分割
現 `@(v: str).to_arr(): arr<str>`
新 `@(v: str).to_text_arr(): arr<str>`

### コードポイント毎に分割、文字配列を取得
現 `@(v: str).to_unicode_arr(): arr<str>`
新 `@(v: str).to_arr(): arr<str>`

### コードポイント毎に分割、コードポイントの数値配列を取得
現 `@(v: str).to_unicode_codepoint_arr(): arr<num>`
新 `@(v: str).to_charcode_arr(): arr<num>`

### UTF-16 コード単位毎に分割、UTF-16 コード単位の文字配列を取得
現 `@(v: str).to_char_arr(): arr<str>`
新 `@(v: str).to_utf16_arr(): arr<str>`

### UTF-16 コード単位毎に分割、UTF-16 コード単位の数値配列を取得
現 `@(v: str).to_charcode_arr(): arr<num>`
新 `@(v: str).to_utf16_charcode_arr(): arr<num>`

### i 番目のにある UTF-16 コード単位の数値を取得
現 `@(v: str).charcode_at(i: num): num | null`
新 `@(v: str).utf16_charcode_at(i: num): num | null`

### i 番目の文字のコードポイントの数値を取得
現 `@(v: str).codepoint_at(i: num): num | null`
新 `@(v: str).charcode_at(i: num): num | null`

**Comment by MineCake147E** [comment]
> * charcode、codepointという命名の分け方をやめ、charcodeで統一します。

コードポイントを`charcode`と称するのは直感に反すると思います。`charcode`の名称を廃する場合でも、コードポイントを`codepoint`、UTF-16コード単位を`utf16_code`とする方が良いかと思います。

**Comment by marihachi** [comment]
ユニコード以外の文字コードを抽象化するという意味で「charcode」を使うようにしましたが、まずかったですか

**Comment by MineCake147E** [comment]
でしたら、C#の`Encoding`のような、文字コード体系を抽象化した概念(オブジェクト?)を導入するのはどうでしょうか。
また、Unicodeは特に複雑なので、`Unicode`配下にUnicode関連の関数を移動するという方策も考えられます。

**Comment by FineArchs** [comment]
> @(v: str).to_unicode_arr → @(v: str).split

https://github.com/aiscript-dev/aiscript/blob/df9d61025ec247e0707fe789185980888b21f30b/docs/primitive-props.md?plain=1#L68-L70
@(v: str).splitはもう別の関数に使われてますわよ

**Comment by FineArchs** [comment]
> また、Unicodeは特に複雑なので、Unicode配下にUnicode関連の関数を移動するという方策も考えられます。

個人的にはこうしたいかもです
更に言うなら`Unicode:` `Utf16:` `Utf8:`に分けたい

**Comment by marihachi** [comment]
比較的古い言語の場合は歴史的にASCIIをベースにした考え方になってると思います。ユニコードが一般的に使われている時代に生まれていないためです。
わざわざそれに従う必要はないのかなと思いました。
ユニコードをベースに言語のAPIを設計するのであれば、ユニコードの名前空間にわざわざ置く必要はない気がします。
ユニコードは仕様が複雑であるゆえに、細かい変換関数はそれぞれの名前空間において良いと思います。

**Comment by marihachi** [comment]
> > @(v: str).to_unicode_arr → @(v: str).split
> 
> https://github.com/aiscript-dev/aiscript/blob/df9d61025ec247e0707fe789185980888b21f30b/docs/primitive-props.md?plain=1#L68-L70
> 
> 
> @(v: str).splitはもう別の関数に使われてますわよ

見逃してました
別の名前を考えます

**Comment by marihachi** [comment]
通常のユニコード操作はstrのプリミティブプロパティに置く

他のコード表現への変換はstd APIにする
例: `Ascii:*`、`Utf8:*`、`Utf16:*`

でどうでしょうか？

**Comment by FineArchs** [comment]
うーん、そもそもコードポイントを気にしなければならない時点で
> ユニコードは仕様が複雑であるゆえに、細かい変換関数はそれぞれの名前空間におくというのは賛成です。

で言う所の「細かい変換関数」に該当すると思うんですよね

**Comment by marihachi** [comment]
> ユニコードやそれ以外の文字コードを抽象化するという意味で「charcode」を使うようにしました。
> 
> ユーザーは取得される文字コードがユニコードのコードポイントであるということを意識することなくAPIを扱うことができます。 言語のプライマリな機能として文字コードを取得するAPIを設計するのであれば、charcodeとする方が良いのかなと思いました。 名前をcodepointとした場合は、それはUnicodeの用語なので、今後の設計変更で文字コードがユニコードのコードポイントではなくなった場合に名前の変更が必ず必要になります。

ちょっと考えました。これは撤回します。
ユニコードを前提にはするけれど抽象化まではしなくても良いかもです。
codepointって名前を使いますか

**Comment by marihachi** [comment]
> うーん、そもそもコードポイントを気にしなければならない時点で
> 
> > ユニコードは仕様が複雑であるゆえに、細かい変換関数はそれぞれの名前空間におくというのは賛成です。
> 
> で言う所の「細かい変換関数」に該当すると思うんですよね

あまり意図が伝わってこないので詳しく教えてください

**Comment by marihachi** [comment]
ユニコードはコードポイントと、バイト表現(符号化方式と言われてるもの？)の2つがあると思ってます。
バイト表現の変換についてはstd APIに置くというのはどうでしょう？

**Comment by FineArchs** [comment]
> うーん、そもそもコードポイントを気にしなければならない時点で
> 
> > ユニコードは仕様が複雑であるゆえに、細かい変換関数はそれぞれの名前空間におくというのは賛成です。
> 
> で言う所の「細かい変換関数」に該当すると思うんですよね

Unicodeのコードポイントという概念自体専門知識なので、まるごと分離したいという意図です

**Comment by marihachi** [comment]
確かにそうかも...

**Comment by FineArchs** [comment]
ただ、今のところプリミティブプロパティには名前空間が使えないのでどうしましょうか

**Comment by marihachi** [comment]
> ただ、今のところプリミティブプロパティには名前空間が使えないのでどうしましょうか

ユニコードの変換周りはすべてstdに置く形ですかね

**Comment by marihachi** [comment]
方向性が変わってきたので、草案2を準備していきます

**Comment by marihachi** [comment]
Draft 2を提案したのでクローズします
