### ISSUE TITLE
这个项目有官方文档吗……

### ISSUE THREAD

**Issue by Drun1baby** [aiscript-dev/aiscript#573]

**Comment by FineArchs** [comment]
[README](https://github.com/aiscript-dev/aiscript/blob/master/README.md) and [docs/*.md](https://github.com/aiscript-dev/aiscript/tree/master/docs) are everything that is currently available as official documentation (written in Japanese).
English version is available at [translations/en](https://github.com/aiscript-dev/aiscript/tree/master/translations/en), but it is not well maintained and the information is not up-to-date.
