### ISSUE TITLE
空の配列に対する`(arr).reduce()`が正しく診断されない

### ISSUE THREAD

**Issue by zawa-ch** [aiscript-dev/aiscript#598]
空の配列に対して`arr.reduce(fn)`を実行した場合のエラーが環境によってまちまちです。

## 再現可能なAiScriptコードと環境
```aiscript
[].reduce(@(b,c,n){})
```

- AiScript:
  - 2024-03-20 00:00:00 +09:00 時点で[`gh-pages`](https://github.com/aiscript-dev/aiscript/tree/01a0d9d0333b365638fe8ba417cd250efce05536)にデプロイされているバージョン
  - Misskey 2024.3.1 に含まれるAiScript `0.17.0`
- Browser:
  - Mozilla Firefox 123.0.1 (in Linux 6.6.19-1-MANJARO x86_64)
  - Vivaldi 6.6.3271.50 stable (in Linux 6.6.19-1-MANJARO x86_64)

## 期待される動作
`null`、空の配列`[]`、もしくはerror型などの定義された値が返る、もしくは正しく診断されたエラーによって終了する

## 実際の動作
`internal: i is undefined`などの未定義なランタイムエラーによって終了する

**Comment by zawa-ch** [comment]
```aiscript
[].reduce(@(b,c,n){},null)
```

のように初期値を指定するとエラーが発生しなくなることを確認しています。

**Comment by zawa-ch** [comment]
デバッグすると
https://github.com/aiscript-dev/aiscript/blob/56055f11cd1de5a39ae9206d378731427ced57ae/src/interpreter/primitive-props.ts#L191
で`accumulator: undefined`だったことも確認しました。
返ってきた`undefined`を処理するタイミングでエラーになっているものと推測されます。
![20240320_004118](https://github.com/aiscript-dev/aiscript/assets/23190298/0fc4af66-4dbf-4b3d-a9dd-cd166f846c5e)

**Comment by salano-ym** [comment]
`arr.reduce`は初期値を指定しない場合`arr[0]`を初期値として参照するので空配列でエラーになるのは仕様かと思います。
配列の範囲外アクセスはエラーなので。

エラー内容はもっと分かりやすくしてもいい思います。

**Comment by zawa-ch** [comment]
空配列に対する`(arr).reduce(fn)`はエラー、把握しました

どのみち関数の外に`undefined`が漏れているということは未定義動作として扱われているのでassertしたほうが良いかもしれないですね
