### ISSUE TITLE
行番号を扱う際に複数行コメントが1行としてカウントされている

### ISSUE THREAD

**Issue by salano-ym** [aiscript-dev/aiscript#603]
複数行にまたがるコメントが1行としてカウントされるため、エラー位置の特定が難しくなってしまう。
```
/*

*/
<<<syntax error>>>
```
Expect: `Parsing error. (Line 4:1)`
Actual: `Parsing error. (Line 2:1)`

**Comment by FineArchs** [comment]
これ確かnextでは直ってるやつだったと思います
現行でも直した方がいいですかね？

**Comment by salano-ym** [comment]
next取り入れまでまだかかるなら修正した方がいいかも？

**Comment by uzmoi** [comment]
PR作ります。
