### ISSUE TITLE
0.18.0をリリースしたい

### ISSUE THREAD

**Issue by salano-ym** [aiscript-dev/aiscript#624]
進行中の現行向けPRを処理したら0.18.0をリリースしたい
### PR
- [ ] #600
- [ ] #608
- [x] #620
- [ ] #621 
- [ ] #622 
- [x] #623

### マージ済の更新内容
https://github.com/aiscript-dev/aiscript/blob/bc0c5a9898efc9dbe0e1b4072a1925ad7294ec0e/CHANGELOG.md?plain=1#L3-L14

**Comment by FineArchs** [comment]
うーん、途中ですけど一回リリースしちゃいます？
nextが先延ばしになりすぎな気もしますけど

**Comment by salano-ym** [comment]
nextってどれくらい進んでるんでしょう？

**Comment by FineArchs** [comment]
https://github.com/aiscript-dev/aiscript/issues/396
↑
初期から見えていた部分はこんな感じで、加えて未解決issueがいくつかある感じだと思います

**Comment by FineArchs** [comment]
そうですね、一回リリースしちゃいましょうか

**Comment by FineArchs** [comment]
@syuilo どうでしょう？

**Comment by FineArchs** [comment]
@syuilo 👀

**Comment by syuilo** [comment]
YOSASOU

**Comment by FineArchs** [comment]
CHANGELOGの一番上のバージョンだけ変えてbuild&publishお願いします

**Comment by FineArchs** [comment]
@syuilo と言うわけでbuildとpublishだけお願いします

**Comment by salano-ym** [comment]
できればPR終わってからにしたいですがもうしますか？

**Comment by FineArchs** [comment]
まああまり延ばすと良くないので…（いつ終わるかわかりませんし）

**Comment by FineArchs** [comment]
@salano-ym nextの前にもう一回くらいマイナーリリースをとると思うので、そこに引き継ぎでどうでしょう？

**Comment by salano-ym** [comment]
一旦出しますか

**Comment by FineArchs** [comment]
@syuilo 👀

**Comment by syuilo** [comment]
やるか

**Comment by FineArchs** [comment]
@kakkokari-gtyih 今のところしゅいろさんしかできないですね…

**Comment by FineArchs** [comment]
@syuilo バージョン変え系の作業は済んでいるので`npm run build`して`npm publish`だけお願いします

**Comment by FineArchs** [comment]
https://www.npmjs.com/package/@syuilo/aiscript/v/0.18.0
🙏🙏🙏
