### ISSUE TITLE
ネストした名前空間下の変数を参照できない

### ISSUE THREAD

**Issue by takejohn** [aiscript-dev/aiscript#629]
名前空間をネストしてもエラーになりませんが、その配下の変数を参照しようとするとエラーが発生します。

## 再現方法
次のような AiScript コードを実行すると
```
:: Ns1 {
  :: Ns2 {
    let a = 42
  }
}

<: Ns1:Ns2:a
```
次のエラーが発生します。
```
Runtime: No such variable 'Ns1:Ns2:a' in scope '<root>'
```

**Comment by FineArchs** [comment]
これ確か未実装でTODOになってるやつですね
そんなに難しい仕組みではなかったはずなので早めに実装したいという気持ちはあります

**Comment by takejohn** [comment]
> https://github.com/aiscript-dev/aiscript/blob/4fde229003205f92c06613630a57663d4a3a2b72/src/interpreter/index.ts#L214-L216
> 
> これ確か未実装でTODOになってるやつですね
> そんなに難しい仕組みではなかったはずなので早めに実装したいという気持ちはあります

ありがとうございます。
手を加えてみようと思います。
