### ISSUE TITLE
リリースされたバージョンのコミットタグを付ける

### ISSUE THREAD

**Issue by salano-ym** [aiscript-dev/aiscript#638]
過去バージョンを見たい時に便利なのでタグを付けたい

**Comment by FineArchs** [comment]
どのくらい遡ります？

**Comment by salano-ym** [comment]
とりあえず使用者が増えてきた0.12.0前後まであると嬉しいですね

**Comment by FineArchs** [comment]
923d74b5aae39adf2ff6bb71b98734e4348f9a60 0.12.0
5286ae68fe245e5cda26f5919e1cec06403cb2c6 0.12.1
4ccd0ea2dc56b4279476c33406c1c70971ec9a6f 0.12.2
b47393d009650352d8482e81cbb7db950ba0c412 0.12.3
25ba52041d3b76d22125e727c1c30c69849d215c 0.12.4
00b70470ff38817a7bccbe6c1ccb571b4c33f8e7 0.13.0
5460323e2d450d036536556bbe96a23be62577c7 0.13.1
a1234cd067f8eb8451734651d8efd58dcb92ec39 0.13.2
b4e5f756cea30c6fd7b8a94afe4f38c930ccf164 0.13.3
04c2e2f94bbbc1dda7fde382a5d90335efb9cdc0 0.14.0
6cd03a2ab3523da7e8ae2c995efc0657ba9cc2ea 0.14.1
0959a3e29c694a24bb8056b5d0b974da77e592b0 0.15.0
7e1317bd407d63af7ad2e14afc00d807fac7ca31 0.16.0
5a58dfee1e658f322e615396853b21e67d5bbbfa 0.17.0
8d4dbaf237e75d4e3fe4495b4bb683496eb90f27 0.18.0

**Comment by FineArchs** [comment]
https://github.com/aiscript-dev/aiscript/tags
付けました
