### ISSUE TITLE
nullチェックを意図している所でfalsyな非null値も弾かれている

### ISSUE THREAD

**Issue by salano-ym** [aiscript-dev/aiscript#644]
例
https://github.com/aiscript-dev/aiscript/blob/17f0c85fee7a61b70e2b1d568cdb55266718efcf/src/interpreter/lib/std.ts#L185-L186
対策
`v!=null`や`v ?? other`を使う

**Comment by FineArchs** [comment]
https://github.com/aiscript-dev/aiscript/blob/17f0c85fee7a61b70e2b1d568cdb55266718efcf/src/interpreter/value.ts#L40
こういう場所は`Value`か`undefined`しか入ってこないのでそれで問題ないです

**Comment by salano-ym** [comment]
`v.value`が`0`だと`v?.value || Date.now()`で`Date.now()`が返ってしまうようです

**Comment by FineArchs** [comment]
なるほど、確かにそちらの`||`は`??`に変えないとまずそうですね

**Comment by salano-ym** [comment]
テスト追加しときます
