### ISSUE TITLE
二項演算子の糖衣構文のノードにlocが無い

### ISSUE THREAD

**Issue by uzmoi** [aiscript-dev/aiscript#646]
`&&`や`==`などの二項演算子をパースしたときのand/orノードやcallノードとそのtargetのidentifierノードにlocプロパティが無いです。

アサインしていただければ追加するPR作りますが、pegのパーサーの話でnextには関係ないので、0.18.1を出さずに次のリリースで新しいパーサーになるなら閉じます。

**Comment by FineArchs** [comment]
nextの前にもう一回マイナーリリースを挟む予定なのでやって頂けると助かります。よろしくお願いします。
