### ISSUE TITLE
arr.sortを安定ソートにする

### ISSUE THREAD

**Issue by salano-ym** [aiscript-dev/aiscript#656]
## 現状
compの結果が同じである要素は元の逆順になってしまう。

## 変更方法
ここを`compValue.value <= 0`にするだけ。
https://github.com/aiscript-dev/aiscript/blob/5c7f11f763ab4e9a19ebadb9afc9a0621ad107c3/src/interpreter/primitive-props.ts#L248

## どこで変更するか
破壊的なのでNextにする？

**Comment by FineArchs** [comment]
> 破壊的なのでNextにする？

一応それがいいかも？
