### ISSUE TITLE
Math:gen_rngのテストのバグ

### ISSUE THREAD

**Issue by salano-ym** [aiscript-dev/aiscript#659]
`Math:gen_rng`のテストで、`test(seed1)`と`test(seed2)`が常に異なることを期待しているが、実際は一致することもありえる。
一致してしまうとテストが失敗する。
https://github.com/aiscript-dev/aiscript/blob/9e618049b5753b26d7527ee736dff10d65289b18/test/index.ts#L3303-L3316

**Comment by uzmoi** [comment]
「シードが違うなら乱数列の最初の数が違う」ことは乱数生成器に必須の要件ではないものの、別のシードから同じ数が出てくることは現実的にはほぼないのではないかなと思います。
シードが乱数に影響を与えることのテストとしてあってもいいのでは。

**Comment by FineArchs** [comment]
もうちょっとちゃんとやるなら0~99の乱数同士で100回試行して、重複が5回以下ならOKみたいなことをするといいかもしれない
この場合、乱数が正常ならテスト失敗率は単純に考えて0.05%ほどのはず
https://www.wolframalpha.com/input?i2d=true&i=Sum%5B%5C%2840%29Combinations%5C%2840%29100%5C%2844%29k%5C%2841%29*Power%5B0.01%2Ck%5D*Power%5B0.99%2C100-k%5D%5C%2841%29%2C%7Bk%2C6%2C100%7D%5D

**Comment by salano-ym** [comment]
> 0~99の乱数同士で100回試行して、重複が5回以下ならOK

その方針で修正してみます

**Comment by uzmoi** [comment]
乱数の範囲見てなかった……
乱数の範囲が十分広げれば大丈夫とは思いますが、試行回数も増やしたほうがいいですね。
