### ISSUE TITLE
CHANGELOGが毎回conflictするのが煩わしい

### ISSUE THREAD

**Issue by FineArchs** [aiscript-dev/aiscript#662]
CHANGELOGの一番下に更新事項を毎回書いていくとマージの仕様上？毎回conflictすることになる
## 対策案
changelogsフォルダを用意し、そこに1コミットごとに1ファイルでlogを書く
そしてリリースの際にまとめてCHANGELOGにくっつける

**Comment by salano-ym** [comment]
こういう感じですかね
- `/changelogs/arr-at.md`
  ```
  - arr.atを追加
  ```
- `/changelogs/arr-insert.md`
  ```
  - arr.insertを追加
  ```

**Comment by salano-ym** [comment]
統合は手作業だと漏れ等ありそうだから自動でやってほしいところ

**Comment by FineArchs** [comment]
> ちょっと調べてみたところマージドライバをunionにしてみる解決法というのがあるらしいです（未検証）

出来たら面白そうですが、github上でやるのが難しそうな感じがしますね…

**Comment by FineArchs** [comment]
> こういう感じですかね
> 
> * `/changelogs/arr-at.md`
>   ```
>   - arr.atを追加
>   ```
> * `/changelogs/arr-insert.md`
>   ```
>   - arr.insertを追加
>   ```

これは今思いついたのですが、devとnextで分けるとnextをdevに追従させる時のいざこざが減りそうですね
