### ISSUE TITLE
インタプリタのエラーハンドリングhookでabortしないようにしたい

### ISSUE THREAD

**Issue by kakkokari-gtyih** [aiscript-dev/aiscript#710]
AiScriptのコードがエラーで停止しても同じインタプリタを使いまわす処理があるが、err hookが設定されている場合に限ってabortが呼ばれてしまい、以降に別のAiScriptコードを実行させる際にも全く動作しなくなる問題を回避したい

Related to https://github.com/misskey-dev/misskey/pull/14117, https://github.com/misskey-dev/misskey/issues/14050

**Comment by FineArchs** [comment]
「一箇所がエラー出てるのに他の所が動きっぱなしだとなんかややこしいことになりそう？」という感じでabortをつけた覚えがありますが、まあやり過ぎでしたね。

オプトインでabortする設定にできるようにするくらいはしたいかもです。

**Comment by FineArchs** [comment]
> > オプトインでabort
> 
> この挙動に頼っている実装（そんなものあるのか？）が壊れる可能性があるので逆でもいい気がした

仕様のデザインとしては、より一般的であろうユースケースの方をデフォルトにしたい気持ちはあるんですよね
とはいえ破壊的は破壊的なので、一旦オプトアウトの形にしてnextからオプトインに入れ替えるとかが良さそうですかね？
