### ISSUE TITLE
0.19.0のリリース

### ISSUE THREAD

**Issue by FineArchs** [aiscript-dev/aiscript#716]
そろそろ0.19.0をリリースしたいです。

## Changes
- `Date:year`系の関数に0を渡すと現在時刻になる問題を修正
- シンタックスエラーなどの位置情報を修正
- `arr.reduce`が空配列に対して初期値なしで呼び出された時、正式にエラーを出すよう
- `str.pad_start`,`str.pad_end`を追加
- `arr.insert`,`arr.remove`を追加
- `arr.sort`の処理を非同期的にして高速化
- `arr.flat`,`arr.flat_map`を追加
- `Uri:encode_full`, `Uri:encode_component`, `Uri:decode_full`, `Uri:decode_component`を追加
- `str.starts_with`,`str.ends_with`を追加
- `arr.splice`を追加
- `arr.at`を追加
- For Hosts: エラーハンドラ使用時、InterpreterのオプションでabortOnErrorをtrueにした時のみ全体のabortを行うように

また、0.19.0の次はnextのリリースにしようと考えています。

**Comment by FineArchs** [comment]
リリースTODO

- [ ] ある程度の人数の同意を得る
- [ ] `npm run pre-release`を実行してリリース用コミットを作り、pushする
- [ ] しゅいろさんに`publish`してもらう

リリース後TODO
- [ ] nextをmasterに合流させる
- [ ] [publish-nightly](https://github.com/aiscript-dev/aiscript/blob/e5fae94892abde3388a7e991b85fbf3e2cea256b/.github/workflows/publish-nightly.yml)からnextを削除
- [ ] package.jsonのバージョンを次リリース用に上げる
  - `0.20.0`? `1.0.0`?

**Comment by syuilo** [comment]
YOSASOU

**Comment by FineArchs** [comment]
ある程度の人数の同意を得たのでリリース作業に移ります。

**Comment by FineArchs** [comment]
@syuilo リリース作業は終わったのでpublishをお願いします。

**Comment by syuilo** [comment]
done

**Comment by FineArchs** [comment]
🙏🙏🙏

**Comment by syuilo** [comment]
🙏

**Comment by syuilo** [comment]
Nextの変更一覧ってどこで見れるっけ

**Comment by FineArchs** [comment]
[unreleased](https://github.com/aiscript-dev/aiscript/tree/aiscript-next/unreleased)フォルダから確認できます。

また、#720 に現在の分を掲載しておきましたので、よろしければそちらをどうぞ。
