### ISSUE TITLE
ノードの終了位置の追加

### ISSUE THREAD

**Issue by uzmoi** [aiscript-dev/aiscript#722]
nextのパーサーだとlocに入るのがノードの開始位置のみになっていますが、これを以前のパーサーと同じ情報が取れるようにしたい。
言語処理系を作っていると欲しくなります。

`CharStream`に`getPos`メソッドがあり、これが返す型が`{ line: number, column: number }`です。
なので、これを`Position`として、`{ start: Position, end: Position }`を`Loc`としたい。
https://github.com/aiscript-dev/aiscript/blob/6634788b4fe33699e65e8fd43a88b0b6eeaa269b/src/parser/streams/char-stream.ts#L48

**Comment by FineArchs** [comment]
startとendの情報も取れるようにするのは賛成ですが、line・columnと同じ所にまとめてしまった方が取り回しが楽そうな気がします。

**Comment by uzmoi** [comment]
@FineArchs 同じところにまとめるというと？

**Comment by FineArchs** [comment]
@uzmoi 
すみません、色々勘違いしていました。最初の案で良いと思います。

**Comment by marihachi** [comment]
良いと思います！
