### ISSUE TITLE
Question: IRQはなぜ必要？

### ISSUE THREAD

**Issue by marihachi** [aiscript-dev/aiscript#746]
IRQは300ステップごと(0~299)に発生させていますが、IRQ発生時は5ms遅延させているだけで特に何をしてるわけでもないようです。
これは何のための処理ですか？

**Comment by uzmoi** [comment]
無限ループするコードを実行したときにホスト側がハングしてしまうことへの対策だと思います。

**Comment by marihachi** [comment]
そんな感じみたいですね
頻度を変えてみたり、待ち時間を変えてみるとパフォーマンスにそこそこ影響を与えてるみたいです。

**Comment by FineArchs** [comment]
related: #665
