### ISSUE TITLE
fn.argsの命名を見直す

### ISSUE THREAD

**Issue by marihachi** [aiscript-dev/aiscript#750]
関数の仮引数はargsではなくparamsとする方が自然なため
fn.argsはfn.paramsに変更したい。

**Comment by FineArchs** [comment]
`args`より`params`が自然だという気はあまりしませんが、そういう文脈があるのですか？

**Comment by uzmoi** [comment]
不自然というほどではないと思いますが、一緒だと混乱するので区別したいです。
区別するときは実引数はargument、仮引数はparamatorとなります。
現在のfnの呼び出しの実装ではargdefという変数名が使われていますが、これよりはparamの方がわかりやすいと思います。

参考までにESTreeのFunctionsの定義→https://github.com/estree/estree/blob/master/es5.md#functions

**Comment by FineArchs** [comment]
なるほど、実引数と仮引数の呼び分けは初めて知りました。ありがとうございます。
そういうことであれば`params`に変更するのは良さそうですね。
