### ISSUE TITLE
let false = 'hoge'がエラーにならない

### ISSUE THREAD

**Issue by FineArchs** [aiscript-dev/aiscript#773]
https://github.com/aiscript-dev/aiscript/actions/runs/10644756798/job/29509847385?pr=769

```
let true = 1
var false = 2
let null = 3
```
といった文がエラーにならず、素通りしてしまうバグが発生しているようです。

分割代入の都合上、パースエラーにするのは難しい面もありますが、せめてランタイムエラーは出て欲しいかも

**Comment by FineArchs** [comment]
あと現行のテスト（[keyword.ts](https://github.com/aiscript-dev/aiscript/blob/master/test/keywords.ts))だとシンタックスエラーじゃないと弾かれるのでそこの調整も必要

**Comment by uzmoi** [comment]
#763 でここの実装ミスってるせいですね。
https://github.com/aiscript-dev/aiscript/blob/6dd60a589fe4469829fb2ac9d57e17f8c8a6b201/src/parser/plugins/validate-keyword.ts#L61-L68
