### ISSUE TITLE
REPLの機能強化

### ISSUE THREAD

**Issue by takejohn** [aiscript-dev/aiscript#849]
簡単に短いコードの実験ができるようにしたい

**Comment by uzmoi** [comment]
一応/console.jsがありますが、パッケージにCLIを追加するということですか？

**Comment by uzmoi** [comment]
であればpackage.jsonに追記だけすれば良さそうですが、現状のconsole.jsだと実行ごとに変数が引き継がれないようなので、直してscripts/repl.mjsに移動したいですかね

**Comment by takejohn** [comment]
終了するコマンドが`exit`だと変数名と衝突しそうなので`.exit`みたいに変えたいですね
複数行入力にも対応したいです(たぶんUnexpected Token: EOFをcatchして継続するようにしたらできる)
